[package]
name = "cargo-script"
version = "0.1.5"
authors = ["Daniel Keep <daniel.keep@gmail.com>"]

description = "A Cargo subcommand designed to let people quickly and easily run Rust \"scripts\" which can make use of Cargo's package ecosystem."
repository = "https://github.com/DanielKeep/cargo-script"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["cargo", "script"]

[dependencies]
env_logger = "0.3.1"
hoedown = "3.0.3"
lazy_static = "0.1.15"
log = "0.3.1"
regex = "0.1.44"
rustc-serialize = "0.3.16"
shaman = "0.1.0"
time = "0.1.25"
toml = "0.1.20"
curl = "0.2.18"

[dependencies.clap]
version = "1.4.5"

# Disable the "color" feature because it just outputs garbage on Windows.
default-features = false
features = ["suggestions"]

[target.i686-pc-windows-gnu.dependencies]
ole32-sys = "0.1.0"
shell32-sys = "0.1.1"
winapi = "0.2.4"

[target.x86_64-pc-windows-gnu.dependencies]
ole32-sys = "0.1.0"
shell32-sys = "0.1.1"
winapi = "0.2.4"

[dev-dependencies]
scan-rules = "0.1.1"
tempdir = "0.3.4"

[profile.release]
lto = true
